export const mockUsers = [
  {
    name: "Brenda Jakubowski",
    username: "Darby.Haag",
    email: "Cicero_Hermann24@gmail.com",
    address: {
      street: "Jaylen Underpass",
      suite: "Apt. 134",
      city: "Lake Adellaview",
      zipcode: "39704-2194",
      geo: {
        lat: "-63.1949",
        lng: "114.8543",
      },
    },
    phone: "825-356-9347",
    website: "candida.name",
    company: {
      name: "Kohler - Reinger",
      catchPhrase: "Managed context-sensitive solution",
      bs: "streamline scalable paradigms",
    },
  },
  {
    name: "Miss Linda Cruickshank",
    username: "Garrison.Bashirian74",
    email: "Eliezer_Considine@gmail.com",
    address: {
      street: "Bella Courts",
      suite: "Suite 755",
      city: "Joannyside",
      zipcode: "89269-5713",
      geo: {
        lat: "53.7258",
        lng: "87.7036",
      },
    },
    phone: "542-355-4727",
    website: "verna.org",
    company: {
      name: "Goldner, Buckridge and Murphy",
      catchPhrase: "Function-based global strategy",
      bs: "envisioneer front-end web services",
    },
  },
  {
    name: "Toby Botsford",
    username: "Lillie13",
    email: "Crawford.Crona39@yahoo.com",
    address: {
      street: "King Island",
      suite: "Apt. 707",
      city: "Kuhicmouth",
      zipcode: "03458",
      geo: {
        lat: "33.1102",
        lng: "-137.8688",
      },
    },
    phone: "610.851.6964",
    website: "madelyn.com",
    company: {
      name: "Sauer - Kautzer",
      catchPhrase: "Compatible foreground internet solution",
      bs: "optimize mission-critical action-items",
    },
  },
  {
    name: "Mr. Erika Witting",
    username: "Miguel7",
    email: "Paige10@gmail.com",
    address: {
      street: "Turcotte Stream",
      suite: "Apt. 539",
      city: "Lake Connor",
      zipcode: "89374-6601",
      geo: {
        lat: "15.2346",
        lng: "-88.5063",
      },
    },
    phone: "300.574.1430",
    website: "alford.name",
    company: {
      name: "Armstrong, Rogahn and Dickens",
      catchPhrase: "Multi-channelled uniform installation",
      bs: "visualize value-added markets",
    },
  },
  {
    name: "Maurice Wyman",
    username: "Leilani_Bauch31",
    email: "Rick.Beahan37@gmail.com",
    address: {
      street: "Kub Vista",
      suite: "Suite 514",
      city: "North Athena",
      zipcode: "47394-9021",
      geo: {
        lat: "-44.5055",
        lng: "147.0530",
      },
    },
    phone: "1-309-817-5459",
    website: "ezekiel.name",
    company: {
      name: "Skiles - Gottlieb",
      catchPhrase: "Synergistic bandwidth-monitored knowledge base",
      bs: "facilitate collaborative infrastructures",
    },
  },
  {
    name: "Ella Douglas",
    username: "Hildegard.Morar73",
    email: "Otis.Douglas@gmail.com",
    address: {
      street: "Rick Rest",
      suite: "Suite 592",
      city: "West Laurianneburgh",
      zipcode: "62546",
      geo: {
        lat: "29.4694",
        lng: "139.4961",
      },
    },
    phone: "228-287-5921",
    website: "lola.name",
    company: {
      name: "Conroy, Rutherford and Renner",
      catchPhrase: "Ergonomic local leverage",
      bs: "matrix rich methodologies",
    },
  },
  {
    name: "Alexandra Frami",
    username: "Magdalen.Lubowitz13",
    email: "Liliana_Hermiston55@gmail.com",
    address: {
      street: "Grady Mountain",
      suite: "Apt. 515",
      city: "Lake Dina",
      zipcode: "71361",
      geo: {
        lat: "60.6212",
        lng: "122.5843",
      },
    },
    phone: "992.432.6050 x63256",
    website: "idell.com",
    company: {
      name: "Spinka, Armstrong and Maggio",
      catchPhrase: "Virtual intermediate conglomeration",
      bs: "e-enable impactful supply-chains",
    },
  },
  {
    name: "June Kertzmann",
    username: "Destini82",
    email: "Markus7@yahoo.com",
    address: {
      street: "Pacocha Garden",
      suite: "Apt. 173",
      city: "Erdmanland",
      zipcode: "35256-1545",
      geo: {
        lat: "-73.0012",
        lng: "-30.8606",
      },
    },
    phone: "(487) 463-0073",
    website: "yolanda.org",
    company: {
      name: "Wilderman and Sons",
      catchPhrase: "Proactive systematic matrix",
      bs: "brand customized communities",
    },
  },
  {
    name: "Yolanda Johns",
    username: "Vince.Little94",
    email: "Carmel42@gmail.com",
    address: {
      street: "Conrad Village",
      suite: "Apt. 307",
      city: "Port Brandt",
      zipcode: "71237",
      geo: {
        lat: "-70.4599",
        lng: "-106.7105",
      },
    },
    phone: "(969) 762-5661 x0717",
    website: "dangelo.biz",
    company: {
      name: "Durgan, Reichel and DuBuque",
      catchPhrase: "Re-engineered discrete hardware",
      bs: "implement killer e-commerce",
    },
  },
  {
    name: "Joan Hackett",
    username: "Colleen_Torp45",
    email: "Nora_Cole@hotmail.com",
    address: {
      street: "VonRueden Hollow",
      suite: "Apt. 984",
      city: "Abnerview",
      zipcode: "99941",
      geo: {
        lat: "20.0837",
        lng: "60.5793",
      },
    },
    phone: "949.627.6756",
    website: "cary.info",
    company: {
      name: "Pouros, Quitzon and Roberts",
      catchPhrase: "Diverse needs-based hardware",
      bs: "envisioneer value-added partnerships",
    },
  },
  {
    name: "Bryant Hamill DVM",
    username: "Miguel.Lindgren5",
    email: "Maia_Cassin85@gmail.com",
    address: {
      street: "Keeling Isle",
      suite: "Suite 922",
      city: "Hettingermouth",
      zipcode: "94014",
      geo: {
        lat: "44.0067",
        lng: "-22.1527",
      },
    },
    phone: "1-370-514-0348 x41493",
    website: "camron.info",
    company: {
      name: "Collins, Kulas and Ernser",
      catchPhrase: "Balanced mobile approach",
      bs: "whiteboard plug-and-play blockchains",
    },
  },
  {
    name: "Eileen Gibson",
    username: "Sofia_Leannon28",
    email: "Kimberly.Kozey@hotmail.com",
    address: {
      street: "Orrin Estates",
      suite: "Suite 278",
      city: "Margaretefurt",
      zipcode: "14078",
      geo: {
        lat: "17.6389",
        lng: "108.2565",
      },
    },
    phone: "961-574-6034",
    website: "teresa.com",
    company: {
      name: "Waters Inc",
      catchPhrase: "Implemented next generation algorithm",
      bs: "visualize distributed architectures",
    },
  },
  {
    name: "Travis Dach",
    username: "Norene26",
    email: "Norval_Koss21@yahoo.com",
    address: {
      street: "Will Road",
      suite: "Suite 601",
      city: "East Olaland",
      zipcode: "43654-8047",
      geo: {
        lat: "6.9074",
        lng: "-39.6201",
      },
    },
    phone: "1-503-230-5851 x396",
    website: "daphnee.com",
    company: {
      name: "O'Hara - Grady",
      catchPhrase: "Reduced attitude-oriented customer loyalty",
      bs: "cultivate sexy ROI",
    },
  },
  {
    name: "Elena Weissnat",
    username: "Jarrell15",
    email: "Jessie_Cruickshank@gmail.com",
    address: {
      street: "Rippin Grove",
      suite: "Apt. 461",
      city: "Krajcikshire",
      zipcode: "79967",
      geo: {
        lat: "27.3270",
        lng: "148.3718",
      },
    },
    phone: "457.924.1081",
    website: "gregoria.org",
    company: {
      name: "Lowe Group",
      catchPhrase: "Optional fault-tolerant approach",
      bs: "utilize next-generation supply-chains",
    },
  },
  {
    name: "Kristin Huel",
    username: "Rae.Ritchie",
    email: "Isabella.Crist@gmail.com",
    address: {
      street: "Dion Flats",
      suite: "Suite 557",
      city: "New Jerrellhaven",
      zipcode: "69227",
      geo: {
        lat: "64.0638",
        lng: "-101.2234",
      },
    },
    phone: "1-558-876-9935 x037",
    website: "mertie.biz",
    company: {
      name: "Haley, Hermiston and Howell",
      catchPhrase: "Assimilated well-modulated capacity",
      bs: "target seamless partnerships",
    },
  },
  {
    name: "Jordan Nienow",
    username: "Ezequiel_Dickinson86",
    email: "Frances9@hotmail.com",
    address: {
      street: "White Fords",
      suite: "Apt. 785",
      city: "Port Alford",
      zipcode: "62315",
      geo: {
        lat: "18.2143",
        lng: "38.8728",
      },
    },
    phone: "1-306-254-4301 x93672",
    website: "jordi.org",
    company: {
      name: "Greenholt Group",
      catchPhrase: "Optimized dedicated hierarchy",
      bs: "strategize visionary niches",
    },
  },
  {
    name: "Justin Raynor",
    username: "Cory_Walker",
    email: "Jan80@gmail.com",
    address: {
      street: "Franecki Street",
      suite: "Apt. 763",
      city: "North Jeramie",
      zipcode: "99779-2601",
      geo: {
        lat: "19.9025",
        lng: "24.0033",
      },
    },
    phone: "217-388-6147",
    website: "erick.info",
    company: {
      name: "Hand and Sons",
      catchPhrase: "Profit-focused actuating migration",
      bs: "transform cross-media functionalities",
    },
  },
  {
    name: "Penny Schmeler",
    username: "Flavio.Mann57",
    email: "Vada.Lesch99@yahoo.com",
    address: {
      street: "Emerson Motorway",
      suite: "Suite 677",
      city: "Piercefurt",
      zipcode: "41952-2445",
      geo: {
        lat: "11.8457",
        lng: "176.2172",
      },
    },
    phone: "(734) 460-6970 x804",
    website: "ward.biz",
    company: {
      name: "Cormier - Aufderhar",
      catchPhrase: "Face to face bandwidth-monitored analyzer",
      bs: "unleash scalable bandwidth",
    },
  },
  {
    name: "Agnes Rutherford",
    username: "Alvah73",
    email: "Cortney92@hotmail.com",
    address: {
      street: "Ebba Roads",
      suite: "Suite 496",
      city: "Lake Idellmouth",
      zipcode: "76307-7185",
      geo: {
        lat: "-4.6102",
        lng: "17.7216",
      },
    },
    phone: "408-238-8782",
    website: "odessa.com",
    company: {
      name: "Hilll - Schulist",
      catchPhrase: "Reverse-engineered value-added firmware",
      bs: "repurpose integrated technologies",
    },
  },
  {
    name: "Lee Klocko",
    username: "Kiel91",
    email: "Shanny59@hotmail.com",
    address: {
      street: "Rod Island",
      suite: "Apt. 460",
      city: "New Billymouth",
      zipcode: "74773",
      geo: {
        lat: "15.2979",
        lng: "83.5565",
      },
    },
    phone: "681-941-1634 x45258",
    website: "haleigh.name",
    company: {
      name: "Block - Lesch",
      catchPhrase: "Cloned logistical projection",
      bs: "leverage extensible e-business",
    },
  },
  {
    name: "Ian Rippin",
    username: "Marianna_Ruecker16",
    email: "Aliya.OKon92@hotmail.com",
    address: {
      street: "Leone Ville",
      suite: "Apt. 235",
      city: "Marielamouth",
      zipcode: "49047-0126",
      geo: {
        lat: "34.1421",
        lng: "-56.1933",
      },
    },
    phone: "873-617-1605",
    website: "adam.name",
    company: {
      name: "Glover, Leuschke and Funk",
      catchPhrase: "Polarised fault-tolerant capability",
      bs: "transition wireless experiences",
    },
  },
  {
    name: "Jenna Bode",
    username: "Everett.Treutel21",
    email: "Lazaro_Kunze@hotmail.com",
    address: {
      street: "Harmony Locks",
      suite: "Apt. 955",
      city: "Lake Mackenzieborough",
      zipcode: "76395-6040",
      geo: {
        lat: "88.5836",
        lng: "89.6053",
      },
    },
    phone: "(727) 831-1389",
    website: "della.com",
    company: {
      name: "Lindgren Inc",
      catchPhrase: "Mandatory 24/7 framework",
      bs: "empower bleeding-edge e-services",
    },
  },
];
